# Generated by Django 5.2.7 on 2025-12-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
